### ISSUE TITLE
Incorrect root url detection for WebSocket with any non-root url path

### ISSUE THREAD

**Issue by ICEFIR** [codercom/code-server#101]
- `code-server` version:  1.0.0
- OS Version: Debian 9, With docker deployment

#### Steps to Reproduce

1. Setup Nginx reverse proxy to a different path - i.e. to something.something.com/vscode/
2. Login works fine, but upon vscode page, it's just a blank page. Client browser console shows its trying to connect to wss://something.somthing.com/, without the correct root-relative path (something.something.com/vscode/), which.... obvious will not work.

Also, I did not find any documentation (or config in general) related to this type of deployment... guess that probably can be improved a bit?

**Comment by idoprz** [comment]
I can also see that getting the webpack_hmr is failing because it looks for it in the host root.

**Comment by MrDetonia** [comment]
I'm having the exact same problem. Nginx is set up to run a reverse proxy under a `/code/` location, headers set to upgrade the connection for websockets, but I see the page trying to make websocket connections, and GET `__webpack_hmr` from my root url.

Outside of using e.g. a subdomain and an entirely new Nginx site, I don't see a feasible solution for this; and I imagine having VSCode exist as a sub-directory may be a common setup.

**Comment by kylecarbs** [comment]
Ah I know the issue.

Updating https://github.com/codercom/code-server/blob/master/packages/ide/src/fill/client.ts#L95 to contain the browser URL should fix this.

**Comment by MrDetonia** [comment]
This seems to have been fixed by #149 

Have built a fresh image from upstream and tested the same setup that was previously broken - all working.

**Comment by si458** [comment]
i have pulled the latest image from https://hub.docker.com/r/codercom/code-server
(March 13, 2019 07:36 PM) and im still getting the 404 error ?

`Firefox can't establish a connection to the server at https://192.168.168.77:32770/__webpack_hmr.`

sample docker-compose file
```
version: '2'
services:
  codeserver:
    image: codercom/code-server:latest
    ports:
      - 8443
    volumes:
      - codeserver:/root/project
volumes:
  codeserver:
    driver: local
```

**Comment by betatim** [comment]
Works well with that fix: https://twitter.com/betatim/status/1106195567892402177

**Comment by si458** [comment]
i have pulled the latest image again this morning from https://hub.docker.com/r/codercom/code-server (March 15, 2019 05:19 AM) and im still getting the 404 error ?
`Firefox can't establish a connection to the server at https://192.168.168.77:32770/__webpack_hmr.`

**Comment by MrDetonia** [comment]
@si458 Odd, as that fix seems to be included in the latest release:
https://github.com/codercom/code-server/blob/2f27b5df8cc37d047ff93bf842c856c97ad74170/packages/ide/src/fill/client.ts#L96

Are you sure it's the same issue / able to post your nginx config?

**Comment by si458** [comment]
@MrDetonia i dont use nginx?
i only use a docker-compose file, nothing special
```
version: '2'
services:
  codeserver:
    image: codercom/code-server:latest
    ports:
      - 8443
    volumes:
      - codeserver:/root/project
    command: --allow-http --no-auth
volumes:
  codeserver:
    driver: local
```

**Comment by MrDetonia** [comment]
@si458 as I understand it, this issue was specific to using a reverse proxy with nginx (see OP). You may be seeing some other issue that is unrelated.

**Comment by si458** [comment]
@MrDetonia your are correct, sorry

ill tag onto the other issue thats been closed but it needs re-opening as its still an issue 
https://github.com/codercom/code-server/issues/141

**Comment by kylecarbs** [comment]
I believe this is fixed. cc: @code-asher

**Comment by code-asher** [comment]
Yup, the websocket uses the same URL that serves `code-server` now.
